### ISSUE TITLE
Doesn't work in fragment, doest it?

### ISSUE THREAD

**Issue by garwanaveen** [jdamcd/android-crop#225]
When I try to crop image in a fragment and call crop function with activity reference (not able to call the same with fragment reference) the call back OnActivityResult is not fired of the fragment instead it goes to the activity's OnActivityResult.
Any suggestions on this ?

**Comment by Lawgrin** [comment]
I had the same issue with another project, what we did was on the activity keep reverence of your FragmentPagerAdapter then with the onActResult just "FragmentPagerAdapter.getFragment()" [we have a custom FragmentPagerAdapter with this function] and then call "fragment.onActivityResult(fee, fie, foo);"

**Comment by alexeykoren** [comment]
Same here. I debugged it a little bit and found that problem is in the REQUEST_PICK = 9162 value. When Activity receives it in onActivityResult() it executes
 int index = requestCode>>16;
if (index != 0) {
// poke active fragments
}
on super.onActivityResult()
while 9162>>16 = 0 so no active fragments are notified. 

Android 6

**Comment by jdamcd** [comment]
If you start the crop from a `Fragment` you'll receive the result on the `Fragment`. It sounds like you're starting, the crop with an `Activity` reference, so you'll get the result on the `Activity`. This is the expected behaviour.
